title: The Bored Physicist 
author: Melissa Mendes
email: 
description: > # this means to ignore newlines until "baseurl:"
  A place to learn and to think about stuff, not necessarily at the same time #physics #blog #coding #LifeIsSoCrazy 
  Um lugar pra aprender e pensar sobre coisas, não necessariamente ao mesmo tempo #fisica #programacao #QueVidaLoka #Batman

# social links
twitter_username: @Meli_Mendes_
github_username:  @MelissaMendes

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
